### ISSUE TITLE
Admin tasks

### ISSUE THREAD

**Issue by raacampbell** [alexanderbrown/masiv#13]
You're the repo boss so you get to do these two things:
- [x] [Choose and add licence](http://stackoverflow.com/questions/31639059/how-to-add-license-to-an-existing-github-project)
- [x] Summary blurb at the top of the page says "MAtlab". I guess it should be "MATLAB"

**Comment by alexanderbrown** [comment]
Summary blurb was deliberate but it doesn't look like it so changed. 

Decided on MIT license for simplicity
