### ISSUE TITLE
masiv_plugin.isPlugin is broken in MATLAB R2016b

### ISSUE THREAD

**Issue by raacampbell** [alexanderbrown/masiv#3]
The code we use to determine if an `.m` file is a plugin fails in MATLAB 2016b onwards. 

```
 masiv_plugin.isPlugin('neuriteTracer.m')
Error using meta.class.fromName
Error: File: /home/xxx/MaSIV_plugins_dev/neuriteTracer/neuriteTracer.m Line: 116 Column: 17
A constructor call to superclass masivPlugin appears after the object is used, or after a return.

Error in masiv_plugin.isPlugin (line 41)
            m=meta.class.fromName(className);
```

**Comment by alexanderbrown** [comment]
Will download new matlab and check it out

**Comment by alexanderbrown** [comment]
Sorry, my misunderstanding - i thought this was in my code but it's in your class for handling installation. On a separate but related note, perhaps a little confusing to have functions called `masivPlugin` and `masiv_plugin`

**Comment by raacampbell** [comment]
Unfortunately it's not just installation. I used `masiv_plugin.isPlugin` to search the plugin paths and populate the plugins menu with whatever it finds there. MaSIV searches for plugins at startup and in R2016b crashes when it finds the first one.

The problem is Line 41 in `masiv_plugin.isPlugin` where it does `m=meta.class.fromName(className)`. This seems to execute the plugin's constructor and it chokes when it reaches the call for executing the superclass constructor [`obj=obj@masivPlugin(caller)`] If you comment out that line it doesn't crash, but of course the plugin won't work either. Ideas?

I created Issue #8 for the renaming.

**Comment by raacampbell** [comment]
This could even be a regression in MATLAB itself, so I'll contact the TMW.

**Comment by raacampbell** [comment]
Ah ha! The problem was, as the error message tried to tell me, that there was a return statement before the constructor call. Only the neurite tracer exhibited the bug and it's [now fixed](https://github.com/raacampbell/neuriteTracer/commit/55f2c2f3c03837dcc56920d2fd184be510d2bff7).
