### ISSUE TITLE
Remove other external plugins

### ISSUE THREAD

**Issue by raacampbell** [alexanderbrown/masiv#5]
The neurite tracer is removed. We need to also remove other "external plugins" leaving only what we deem core plugins.

**Comment by alexanderbrown** [comment]
I'll get up to speed on the plugin system and remove mine

**Comment by alexanderbrown** [comment]
Ok that was easier than I thought. Like the system. 

All should be removed in a05ee3a58456acd4a119ba76c85b650645dd9d27
